name: deploy on push
on: [push]
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code to build server
        uses: actions/checkout@v2
      - name: copy file to server
        uses: appleboy/scp-action@master
        with:
           username: ubuntu
    source : "./html/*"
    target : "/var/www/html"
    strip_components: 1
    timeout: 30s
    command_timeout: 10m
    use_insecure_cipher: false
    rm: false
    debug: false
    overwrite: false
    proxy_port: 8080
    proxy_timeout: 30s
    proxy_use_insecure_cipher: false
